FROM rust:latest AS builder
WORKDIR /app
COPY . .
ARG PACKAGE
RUN cargo build --release -p ${PACKAGE}

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
ARG BINARY
COPY --from=builder /app/target/release/${BINARY} /usr/local/bin/service
CMD ["service"]
