[package]
name = "platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actix-web.workspace = true
chrono = { workspace = true, features = ["serde", "clock"] }
deadpool-redis = "0.15"
futures-util.workspace = true
jsonwebtoken.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
prometheus.workspace = true
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time"] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
uuid = { workspace = true, features = ["v4", "v5", "serde"] }
sqlx = { workspace = true, features = ["runtime-tokio-native-tls", "postgres", "uuid", "chrono"] }
dotenvy.workspace = true


