worker_processes  1;

events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  upstream product_catalog_upstream { server product-catalog:3003; }
  upstream order_service_upstream { server order-service:3005; }
  upstream logistics_upstream { server logistics:3008; }
  upstream analytics_upstream { server analytics:3007; }
  upstream inventory_management_upstream { server inventory-management:3006; }
  upstream user_management_upstream { server user-management:3004; }
  upstream notifications_upstream { server notification:3009; }
  upstream payments_upstream { server payments:3010; }
  upstream supplier_management_upstream { server supplier-management:3011; }

  server {
    listen 8080;

    location /api/products/ {
      proxy_pass http://product_catalog_upstream/;
    }

    location /api/orders/ {
      proxy_pass http://order_service_upstream/;
    }

    location /api/logistics/ {
      proxy_pass http://logistics_upstream/;
    }

    location /api/analytics/ {
      proxy_pass http://analytics_upstream/;
    }

    location /api/inventory/ {
      proxy_pass http://inventory_management_upstream/;
    }

    location /api/user/ {
      proxy_pass http://user_management_upstream/;
    }

    location /api/notification/ {
      proxy_pass http://notifications_upstream/;
    }

    location /api/payment/ {
      proxy_pass http://payments_upstream/;
    }

    location /api/supplier/ {
      proxy_pass http://supplier_management_upstream/;
    }
  }
}

