worker_processes  1;

events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  upstream product_catalog_upstream { server product-catalog:3003; }
  upstream order_service_upstream { server order-service:3004; }
  upstream logistics_upstream { server logistics:3005; }
  upstream analytics_upstream { server analytics:3007; }

  server {
    listen 8080;

    location /api/products/ {
      proxy_pass http://product_catalog_upstream/;
    }

    location /api/orders/ {
      proxy_pass http://order_service_upstream/;
    }

    location /api/logistics/ {
      proxy_pass http://logistics_upstream/;
    }

    location /api/analytics/ {
      proxy_pass http://analytics_upstream/;
    }
  }
}
